name: Cypress Browser Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        spec-file: [spec-1.cy.js, spec-2.cy.js, spec-3.cy.js]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: |
          npx cypress run --browser ${{ matrix.browser }} --spec "cypress/e2e/${{ matrix.spec-file }}"